<?php


namespace app\models;

//require_once 'db/Db.php';
use app\db\Db;

class Users extends Db
{
    public $db;

    public function __Db()
    {
        $this->db = parent::__Db(); // TODO: Change the autogenerated stub
        return $this->db;
    }

    public function getAll()
    {

    }

    public function getById($id)
    {
        return $this->db->getOne("SELECT * FROM users WHERE id=?i", $id);
    }
}